/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aborted: typeof import('./src/components/buyDeal/aborted.vue')['default']
    AddItemModal: typeof import('./src/components/modal/addItemModal.vue')['default']
    Agreed: typeof import('./src/components/buyDeal/Agreed.vue')['default']
    Archived: typeof import('./src/components/buyDeal/archived.vue')['default']
    Block: typeof import('./src/components/block.vue')['default']
    Card: typeof import('./src/components/card.vue')['default']
    ChangeItemModal: typeof import('./src/components/modal/changeItemModal.vue')['default']
    Complete: typeof import('./src/components/buyDeal/complete.vue')['default']
    Container: typeof import('./src/components/container.vue')['default']
    Created: typeof import('./src/components/buyDeal/Created.vue')['default']
    DealPalette: typeof import('./src/components/dealPalette.vue')['default']
    Error: typeof import('./src/components/error.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    'IconCarbon:language': typeof import('~icons/carbon/language')['default']
    'IconCarbon:sun': typeof import('~icons/carbon/sun')['default']
    'IconCharm:candy': typeof import('~icons/charm/candy')['default']
    'IconFa6Regular:bookmark': typeof import('~icons/fa6-regular/bookmark')['default']
    'IconFluent:handshake24Regular': typeof import('~icons/fluent/handshake24-regular')['default']
    'IconIconoir:3dSelectFace': typeof import('~icons/iconoir/3d-select-face')['default']
    'IconPh:paperclip': typeof import('~icons/ph/paperclip')['default']
    LanguageSwitcher: typeof import('./src/components/languageSwitcher.vue')['default']
    LoadCircle: typeof import('./src/components/loadCircle.vue')['default']
    Modal: typeof import('./src/components/modal/modal.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    PagingLine: typeof import('./src/components/pagingLine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search.vue')['default']
    ThemeSwitcher: typeof import('./src/components/themeSwitcher.vue')['default']
    Unsynced: typeof import('./src/components/unsynced.vue')['default']
    UploadImage: typeof import('./src/components/uploadImage.vue')['default']
    ViewItemModal: typeof import('./src/components/modal/viewItemModal.vue')['default']
  }
}
