/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aborted: typeof import('./components/buyDeal/aborted.vue')['default']
    AddItemModal: typeof import('./components/modal/addItemModal.vue')['default']
    Agreed: typeof import('./components/buyDeal/Agreed.vue')['default']
    Archived: typeof import('./components/buyDeal/archived.vue')['default']
    Block: typeof import('./components/block.vue')['default']
    Card: typeof import('./components/card.vue')['default']
    ChangeItemModal: typeof import('./components/modal/changeItemModal.vue')['default']
    Complete: typeof import('./components/buyDeal/complete.vue')['default']
    Container: typeof import('./components/container.vue')['default']
    Created: typeof import('./components/buyDeal/Created.vue')['default']
    DealPalette: typeof import('./components/dealPalette.vue')['default']
    Error: typeof import('./components/error.vue')['default']
    Footer: typeof import('./components/footer.vue')['default']
    LanguageSwitcher: typeof import('./components/languageSwitcher.vue')['default']
    LoadCircle: typeof import('./components/loadCircle.vue')['default']
    Modal: typeof import('./components/modal/modal.vue')['default']
    Navbar: typeof import('./components/navbar.vue')['default']
    PagingLine: typeof import('./components/pagingLine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/search.vue')['default']
    ThemeSwitcher: typeof import('./components/themeSwitcher.vue')['default']
    Unsynced: typeof import('./components/unsynced.vue')['default']
    UploadImage: typeof import('./components/uploadImage.vue')['default']
    ViewItemModal: typeof import('./components/modal/viewItemModal.vue')['default']
  }
}
