/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dealSol from "./deal.sol";
export type { dealSol };
import type * as storeSol from "./store.sol";
export type { storeSol };
export * as factories from "./factories";
export type { Delivery } from "./deal.sol/Delivery";
export { Delivery__factory } from "./factories/deal.sol/Delivery__factory";
export type { StoreUsers } from "./store.sol/StoreUsers";
export { StoreUsers__factory } from "./factories/store.sol/StoreUsers__factory";
